#!/bin/bash

set -e

clear
rm -f image/*
cargo run --bin stones_svg -- "$1" "${@:3}"             > image/board_front.svg
cargo run --bin stones_svg -- "$1" "${@:3}" --blank     > image/board_blank.svg
cargo run --bin stones_svg -- "$1" "${@:3}" --back "$2" > image/board_back.svg
convert image/board_front.svg image/board_front.png
convert image/board_blank.svg image/board_blank.png
convert image/board_back.svg  image/board_back.png
ristretto image/board_front.png
#ristretto image/board_front.svg
zip image/board2.zip image/*

